import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Breadcrumb } from "@/components/ui/breadcrumb"
import { AlertTriangle, Shield, Eye, Users, Brain, Scale } from "lucide-react"

export const metadata = {
  title: "AI Ethics Guidelines - AI Productivity",
  description: "Essential ethical considerations and guidelines for responsible AI tool usage in professional and personal contexts.",
}

export default function AIEthicsPage() {
  const principles = [
    {
      icon: Shield,
      title: "Transparency and Honesty",
      description: "Be open about AI assistance in your work",
      guidelines: [
        "Disclose when AI tools have been used in content creation",
        "Be honest about the extent of AI assistance in your work",
        "Don't present AI-generated content as entirely your own creation",
        "Inform collaborators and clients about AI tool usage when relevant"
      ]
    },
    {
      icon: Eye,
      title: "Accuracy and Verification",
      description: "Maintain responsibility for the accuracy of AI-assisted work",
      guidelines: [
        "Always fact-check important information generated by AI",
        "Verify sources and citations provided by AI tools",
        "Don't rely solely on AI for critical decisions",
        "Understand the limitations and potential biases of AI tools"
      ]
    },
    {
      icon: Users,
      title: "Respect for Others",
      description: "Consider the impact of AI usage on others",
      guidelines: [
        "Respect intellectual property and copyright laws",
        "Don't use AI to create harmful or misleading content",
        "Consider the impact on employment and human creativity",
        "Respect privacy when using AI tools with personal data"
      ]
    },
    {
      icon: Brain,
      title: "Human Agency",
      description: "Maintain human judgment and decision-making",
      guidelines: [
        "Use AI as a tool to enhance, not replace, human thinking",
        "Maintain your critical thinking skills and domain expertise",
        "Make final decisions based on human judgment",
        "Don't become overly dependent on AI assistance"
      ]
    },
    {
      icon: Scale,
      title: "Fairness and Bias",
      description: "Be aware of and mitigate potential biases",
      guidelines: [
        "Recognize that AI tools may have inherent biases",
        "Seek diverse perspectives and sources",
        "Question AI outputs that seem biased or unfair",
        "Strive for inclusive and equitable outcomes"
      ]
    }
  ]

  const scenarios = [
    {
      title: "Academic and Educational Use",
      considerations: [
        "Follow institutional policies on AI tool usage",
        "Cite AI assistance appropriately in academic work",
        "Use AI to enhance learning, not to avoid it",
        "Maintain academic integrity standards"
      ]
    },
    {
      title: "Professional Content Creation",
      considerations: [
        "Disclose AI assistance to clients when contractually required",
        "Ensure final content meets professional standards",
        "Maintain your unique voice and expertise",
        "Respect client preferences regarding AI usage"
      ]
    },
    {
      title: "Business Decision Making",
      considerations: [
        "Use AI insights as one factor among many",
        "Consider the human impact of AI-informed decisions",
        "Maintain accountability for business outcomes",
        "Ensure compliance with industry regulations"
      ]
    },
    {
      title: "Creative Work",
      considerations: [
        "Balance AI assistance with human creativity",
        "Respect the rights of original creators",
        "Be transparent about AI involvement in creative processes",
        "Consider the value of human artistic expression"
      ]
    }
  ]

  const redFlags = [
    "Using AI to create deliberately misleading information",
    "Presenting AI work as entirely human-created when disclosure is required",
    "Using AI to violate privacy or confidentiality",
    "Relying on AI for decisions that could harm others without human oversight",
    "Using AI to plagiarize or infringe on intellectual property",
    "Ignoring known biases or limitations in AI outputs"
  ]

  return (
    <div className="container py-8">
      <Breadcrumb
        items={[
          { label: "Resources", href: "/resources" },
          { label: "AI Ethics", href: "/resources/ai-ethics", current: true }
        ]}
        className="mb-6"
      />

      <div className="mx-auto max-w-4xl">
        <div className="text-center mb-12">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">
            AI Ethics Guidelines
          </h1>
          <p className="mt-4 text-xl text-muted-foreground">
            Responsible practices for ethical AI tool usage
          </p>
          <Badge variant="secondary" className="mt-4">
            Essential Reading
          </Badge>
        </div>

        {/* Introduction */}
        <Card className="mb-12">
          <CardHeader>
            <CardTitle className="text-2xl">Why AI Ethics Matter</CardTitle>
            <CardDescription>
              As AI tools become more powerful and prevalent, using them responsibly is crucial for maintaining trust, quality, and fairness.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              Ethical AI usage isn't just about following rules—it's about ensuring that AI tools enhance human 
              capabilities while respecting human values, rights, and dignity. These guidelines will help you 
              navigate the ethical considerations of AI tool usage in your professional and personal work.
            </p>
          </CardContent>
        </Card>

        {/* Core Principles */}
        <div className="space-y-8 mb-12">
          <h2 className="text-2xl font-bold">Core Ethical Principles</h2>
          
          {principles.map((principle, index) => (
            <Card key={index}>
              <CardHeader>
                <div className="flex items-center gap-4">
                  <div className="rounded-lg bg-primary/10 p-3">
                    <principle.icon className="h-6 w-6 text-primary" />
                  </div>
                  <div>
                    <CardTitle className="text-xl">{principle.title}</CardTitle>
                    <CardDescription>{principle.description}</CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {principle.guidelines.map((guideline, guidelineIndex) => (
                    <li key={guidelineIndex} className="flex items-start gap-2">
                      <div className="w-2 h-2 rounded-full bg-primary mt-2 flex-shrink-0" />
                      <span>{guideline}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Scenario-Specific Guidelines */}
        <div className="mb-12">
          <h2 className="text-2xl font-bold mb-6">Scenario-Specific Guidelines</h2>
          <div className="grid gap-6 md:grid-cols-2">
            {scenarios.map((scenario, index) => (
              <Card key={index}>
                <CardHeader>
                  <CardTitle className="text-lg">{scenario.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    {scenario.considerations.map((consideration, considerationIndex) => (
                      <li key={considerationIndex} className="flex items-start gap-2">
                        <div className="w-1.5 h-1.5 rounded-full bg-muted-foreground mt-2 flex-shrink-0" />
                        <span className="text-sm">{consideration}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Red Flags */}
        <Card className="mb-12 border-destructive/50">
          <CardHeader>
            <div className="flex items-center gap-3">
              <AlertTriangle className="h-6 w-6 text-destructive" />
              <div>
                <CardTitle className="text-xl text-destructive">Ethical Red Flags</CardTitle>
                <CardDescription>
                  Practices to avoid when using AI tools
                </CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {redFlags.map((flag, index) => (
                <li key={index} className="flex items-start gap-3">
                  <AlertTriangle className="h-5 w-5 text-destructive mt-0.5 flex-shrink-0" />
                  <span>{flag}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        {/* Best Practices Summary */}
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl">Best Practices Summary</CardTitle>
            <CardDescription>
              Key takeaways for ethical AI usage
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4 md:grid-cols-2">
              <div>
                <h3 className="font-semibold mb-2 text-green-600">Do:</h3>
                <ul className="space-y-1 text-sm">
                  <li>• Be transparent about AI assistance</li>
                  <li>• Verify important information</li>
                  <li>• Maintain human oversight</li>
                  <li>• Respect others' rights and privacy</li>
                  <li>• Stay informed about AI capabilities and limitations</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold mb-2 text-red-600">Don't:</h3>
                <ul className="space-y-1 text-sm">
                  <li>• Misrepresent AI-generated content</li>
                  <li>• Blindly trust AI outputs</li>
                  <li>• Use AI to harm or deceive others</li>
                  <li>• Ignore potential biases</li>
                  <li>• Become overly dependent on AI</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}