-- Seed data for jobs table
INSERT INTO jobs (id, title, description, image, use_case_count, tags, featured)
VALUES
  ('teacher', 'Teacher', 'Discover how AI can help create engaging lessons, grade assignments, and provide personalized learning experiences for students of all ages.', 'https://images.pexels.com/photos/5212345/pexels-photo-5212345.jpeg', 4, ARRAY['Education', 'Content Creation', 'Automation'], true),
  ('writer', 'Writer', 'Learn how AI tools can assist with research, drafting, editing, and overcoming writer''s block while maintaining your unique voice and style.', 'https://images.pexels.com/photos/3059747/pexels-photo-3059747.jpeg', 5, ARRAY['Content Creation', 'Research', 'Editing'], false),
  ('developer', 'Software Developer', 'Explore how AI can help write, debug, and document code, as well as explain complex programming concepts and accelerate development workflows.', 'https://images.pexels.com/photos/4709285/pexels-photo-4709285.jpeg', 6, ARRAY['Coding', 'Documentation', 'Debugging'], true),
  ('marketer', 'Digital Marketer', 'Find out how AI can create campaigns, analyze data, generate content, and optimize ad performance across multiple channels and platforms.', 'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg', 5, ARRAY['Marketing', 'Analytics', 'Content Creation'], false),
  ('designer', 'Designer', 'Discover how AI can generate ideas, create mockups, assist in various design tasks, and streamline your creative workflow from concept to completion.', 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg', 4, ARRAY['Design', 'Creativity', 'Visualization'], false),
  ('researcher', 'Researcher', 'Learn how AI can help analyze data, find patterns, summarize papers, generate hypotheses, and accelerate the research process across disciplines.', 'https://images.pexels.com/photos/8326324/pexels-photo-8326324.jpeg', 3, ARRAY['Research', 'Data Analysis', 'Summary'], false);

-- Seed data for job_prompt_structures table
INSERT INTO job_prompt_structures (job_id, title, description, example, order_index)
VALUES
  ('teacher', 'Lesson Plan Creation', 'Structure prompts to create comprehensive, standards-aligned lesson plans', E'Create a detailed 45-minute lesson plan for [grade level] [subject] on [topic]. \n\nInclude:\n• Learning objectives aligned with [standards]\n• Materials needed\n• Warm-up activity (5 minutes)\n• Main instruction with examples (20 minutes)\n• Guided practice (10 minutes)\n• Independent practice (8 minutes)\n• Assessment strategy (2 minutes)\n• Differentiation for [specific needs]\n\nMake it engaging and interactive with at least 2 hands-on activities.', 0),
  ('teacher', 'Assessment Design', 'Generate various types of assessments and rubrics', E'Design a [formative/summative] assessment for [grade level] students learning about [topic]. \n\nRequirements:\n• [number] questions of varying difficulty levels\n• Include: [question types - multiple choice, short answer, essay, etc.]\n• Provide detailed answer key\n• Create a 4-point rubric measuring [specific skills/knowledge]\n• Ensure questions are age-appropriate and aligned with learning objectives\n• Include accommodations for diverse learners', 1),
  ('teacher', 'Student Feedback', 'Create constructive, personalized feedback for student work', E'Provide constructive feedback for this [type of assignment] from a [grade level] student.\n\nFocus on:\n• [specific criteria - content knowledge, writing mechanics, creativity, etc.]\n• Highlight 2-3 specific strengths\n• Identify 1-2 areas for improvement with specific examples\n• Suggest concrete next steps for improvement\n• Use encouraging, age-appropriate language\n• Include one thought-provoking question to promote deeper thinking\n\nStudent work: [paste work here]', 2),
  ('teacher', 'Differentiation Strategies', 'Adapt content for diverse learning needs', E'Adapt this lesson on [topic] for [grade level] to meet diverse learning needs:\n\nCreate modifications for:\n1. Students reading below grade level\n2. English language learners (beginner/intermediate)\n3. Students with ADHD/attention challenges\n4. Gifted students needing enrichment\n5. Students with learning disabilities\n\nFor each group, provide specific modifications for:\n• Content (what they learn)\n• Process (how they learn it)\n• Product (how they show learning)\n\nMaintain core learning objectives while ensuring accessibility.', 3),
  
  ('developer', 'Code Generation', 'Generate functional code from requirements', E'Write a [language] function that [specific functionality].\n\nRequirements:\n• [list specific requirements]\n• Input parameters: [describe inputs]\n• Expected output: [describe output]\n• Performance considerations: [if any]\n• Edge cases to handle: [list edge cases]\n\nCode should include:\n• Proper error handling and input validation\n• Clear, descriptive variable names\n• Comprehensive comments explaining logic\n• Unit test examples\n• Documentation string/comments\n\nFollow [coding standards/style guide] and optimize for [performance/readability/maintainability].\n\nAdditional context: [any relevant background information]', 0),
  ('developer', 'Code Review & Debugging', 'Analyze and improve existing code', E'Review this [language] code for issues and improvements:\n\nPlease analyze for:\n\n1. Bugs and potential issues\n   • Logic errors\n   • Runtime exceptions\n   • Edge case handling\n\n2. Performance optimizations\n   • Algorithm efficiency\n   • Memory usage\n   • Database queries (if applicable)\n\n3. Code quality and best practices\n   • Readability and maintainability\n   • Design patterns\n   • SOLID principles adherence\n\n4. Security vulnerabilities\n   • Input validation\n   • Authentication/authorization\n   • Data exposure risks\n\n5. Readability improvements\n   • Variable naming\n   • Function structure\n   • Comments and documentation\n\nFor each issue found, provide:\n• Specific explanation of the problem\n• Suggested solution with code example\n• Priority level (critical/high/medium/low)\n\nCode to review:\n```[language]\n[paste code here]\n```', 1);

-- Seed data for tools table
INSERT INTO tools (id, name, description, long_description, image, category, url, pros, cons, use_cases)
VALUES
  ('chatgpt', 'ChatGPT', 'A versatile AI assistant that can help with writing, answering questions, and creative tasks.', 'ChatGPT is an AI language model developed by OpenAI that can understand and generate human-like text based on the prompts it receives. It excels at conversational AI, content creation, code assistance, research help, and complex problem-solving across virtually any domain.', 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg', 'Language', 'https://chat.openai.com', 
   ARRAY['Versatile for many different writing and thinking tasks', 'Accessible interface with no coding required', 'Can understand context and follow complex instructions', 'Available in both free and paid versions', 'Supports multiple languages', 'Can handle long conversations with context retention'],
   ARRAY['May occasionally produce inaccurate information', 'Limited knowledge cutoff date', 'Text-only output in base version', 'No direct internet access in base version', 'Can be verbose and may need prompting for conciseness'],
   ARRAY['Writing and editing content', 'Answering questions and explaining concepts', 'Brainstorming ideas and creative writing', 'Drafting emails and professional communications', 'Summarizing long text and research', 'Code review and programming assistance', 'Language translation and learning', 'Creating lesson plans and educational content']),
  
  ('midjourney', 'Midjourney', 'An AI art generator that creates images from text descriptions.', 'Midjourney is a leading AI image generation tool that creates stunning, artistic images based on text prompts. Known for its distinctive aesthetic quality and ability to produce highly detailed artwork, it''s particularly popular among artists, designers, and content creators.', 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg', 'Image Generation', 'https://www.midjourney.com',
   ARRAY['Creates highly detailed and artistic images', 'Intuitive prompt system with style modifiers', 'Rapid generation of multiple variants', 'Strong community and sharing features', 'Excellent for concept art and creative projects', 'Regular updates with improved models'],
   ARRAY['Subscription required for all usage', 'Operates primarily through Discord', 'Learning curve for optimal prompt crafting', 'Limited control over specific details', 'Can be expensive for heavy usage', 'Queue times during peak usage'],
   ARRAY['Creating concept art and illustrations', 'Generating marketing visuals and social media content', 'Designing book covers and promotional materials', 'Prototyping visual ideas quickly', 'Creating mood boards and visual references', 'Producing artwork for presentations', 'Generating unique backgrounds and textures']),
  
  ('copilot', 'GitHub Copilot', 'AI coding assistant that suggests code completions based on context.', 'GitHub Copilot is an AI pair programmer powered by OpenAI''s Codex model. It provides intelligent code suggestions, complete functions, and even entire algorithms based on comments and existing code context, dramatically speeding up development workflows.', 'https://images.pexels.com/photos/11035380/pexels-photo-11035380.jpeg', 'Development', 'https://github.com/features/copilot',
   ARRAY['Suggests complete code blocks and functions', 'Integrated with popular IDEs and editors', 'Understands context and programming intent', 'Supports many programming languages and frameworks', 'Helps with documentation and comments', 'Great for learning new languages and patterns'],
   ARRAY['Subscription cost for individual developers', 'May suggest incorrect or outdated patterns', 'Performance varies by language and framework', 'Occasional inappropriate or inefficient suggestions', 'Can create dependency on AI assistance', 'May suggest code with licensing concerns'],
   ARRAY['Accelerating code writing and development', 'Learning new programming languages or frameworks', 'Automating repetitive coding tasks', 'Generating boilerplate code and templates', 'Writing unit tests and documentation', 'Debugging and code optimization suggestions']);

-- Seed data for use_cases table
INSERT INTO use_cases (id, job_id, title, description, difficulty, time_estimate, tools, steps)
VALUES
  ('teacher-lesson-planning', 'teacher', 'AI-Powered Lesson Planning', 'Create engaging, standards-aligned lesson plans in minutes instead of hours using AI tools.', 'Beginner', '15-30 minutes', ARRAY['chatgpt'], 
   '[
     {"title": "Define Your Lesson Parameters", "content": "Start by determining the grade level, subject, topic, learning standards, and time allocation for your lesson. Be specific about any special considerations like student needs or available resources."},
     {"title": "Create a Detailed Prompt", "content": "Open ChatGPT and use the Lesson Plan Creation prompt template. Fill in your specific parameters and requirements. Be explicit about the structure you want and any special elements to include."},
     {"title": "Review and Refine the Generated Plan", "content": "Carefully review the AI-generated lesson plan. Check for alignment with your curriculum standards, age-appropriateness, and engagement factors. Ask ChatGPT to modify specific sections as needed."},
     {"title": "Personalize and Add Your Expertise", "content": "Add your personal teaching style and expertise to the plan. Modify activities based on what you know works well with your specific students. Add relevant examples or materials you already have."},
     {"title": "Create Supporting Materials", "content": "Use ChatGPT to help generate supporting materials like handouts, slide content, discussion questions, or assessment rubrics to complement your lesson plan."}
   ]'),
  
  ('developer-code-review', 'developer', 'AI-Assisted Code Review', 'Use AI to identify bugs, security issues, and performance problems in your code before they reach production.', 'Intermediate', '20-40 minutes', ARRAY['chatgpt', 'copilot'], 
   '[
     {"title": "Prepare Your Code for Review", "content": "Select the code you want to review. This could be a function, class, or module. Make sure it''s complete enough for the AI to understand its purpose and context."},
     {"title": "Create a Detailed Review Request", "content": "Use the Code Review prompt template in ChatGPT. Include the programming language, intended functionality, and any specific concerns you have. Paste your code within code blocks for proper formatting."},
     {"title": "Analyze the AI Feedback", "content": "Review the AI''s analysis carefully. Look for identified bugs, security vulnerabilities, performance issues, and style recommendations. Note that AI isn''t perfect, so use your judgment."},
     {"title": "Implement High-Priority Fixes", "content": "Address critical issues first, such as security vulnerabilities and bugs. Use the AI''s suggested solutions as a starting point, but verify them against best practices."},
     {"title": "Refactor for Improvements", "content": "Implement the suggested optimizations and improvements. You can ask the AI for help with specific refactoring tasks if needed."},
     {"title": "Verify Your Changes", "content": "After implementing changes, run tests to ensure your code still works as expected. You can also ask the AI to review your updated code for any remaining issues."}
   ]');

-- Seed data for glossary_terms table
INSERT INTO glossary_terms (term, definition, category)
VALUES
  ('Artificial Intelligence (AI)', 'The simulation of human intelligence in machines that are programmed to think and learn like humans, performing tasks that typically require human intelligence.', 'Core Concepts'),
  ('Machine Learning (ML)', 'A subset of AI that involves algorithms that enable computers to learn from and make decisions or predictions based on data.', 'Core Concepts'),
  ('Large Language Model (LLM)', 'A type of AI model trained on vast amounts of text data, capable of understanding, generating, and manipulating language in ways that mimic human-like text.', 'AI Models'),
  ('Natural Language Processing (NLP)', 'A field of AI focused on the interaction between computers and human language, enabling machines to understand, interpret, and generate human language.', 'Core Concepts'),
  ('Prompt Engineering', 'The process of crafting effective inputs or instructions for AI systems to produce desired outputs, especially important when working with language models.', 'Techniques');